<a href="https://colab.research.google.com/github/Yap-Yoong-Siew/Machine-Learning/blob/main/ML_finalPCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>




## Written by Yap Yoong Siew s2122194
```



In [ ]:
import pandas as pd
import numpy as np

In [ ]:
x_list = [0.5,1.0,1.5,1.1,1.9,2.2,2.6,2.0,2.5,3.1]
y_list = [0.7,1.1,1.6,0.9,2.2,2.9,2.7,1.6,2.4,3.0]

In [ ]:
df = pd.DataFrame(list(zip(x_list, y_list)),columns =['X', 'Y'])

In [ ]:
X = df.values
print(X)

[[0.5 0.7]
 [1.  1.1]
 [1.5 1.6]
 [1.1 0.9]
 [1.9 2.2]
 [2.2 2.9]
 [2.6 2.7]
 [2.  1.6]
 [2.5 2.4]
 [3.1 3. ]]


In [ ]:
def featureNormalize(X):
    mu = np.mean(X, axis=0)
    X_norm = X - mu
    sigma = np.std(X_norm, axis=0, ddof=1)
    X_norm /= sigma

    return X_norm, mu, sigma

In [ ]:
def pca(X):
    m, n = X.shape
    U = np.zeros(n)
    S = np.zeros(n)
    Sigma = (1 / m) * (X.T.dot(X))
    U, S, V = np.linalg.svd(Sigma)
    
    return U, S

In [ ]:
def projectData(X, U, K):
    Z = np.zeros((X.shape[0], K))
    Z = np.dot(X,  U[:, :K])
    
    return Z

In [ ]:
X_norm, mu, sigma = featureNormalize(X)
U, S = pca(X_norm)

In [ ]:
print(U) # answer to question feature vector with both eigenvector(a)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [ ]:
K = 1 # target is 1D data
Z = projectData(X_norm, U, K)

print(Z) # answer to new data set (2D-1D) (b)

[[ 2.17864821]
 [ 1.40873323]
 [ 0.55528487]
 [ 1.48864371]
 [-0.29454058]
 [-1.14074313]
 [-1.32230152]
 [ 0.11950342]
 [-0.98454508]
 [-2.00868312]]
